# Generated by Django 3.2.4 on 2021-06-21 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliver_date', models.DateField(auto_now_add=True, verbose_name='Дата доставки')),
                ('transporter', models.CharField(max_length=100, unique_for_date=models.DateField(auto_now_add=True, verbose_name='Дата доставки'), verbose_name='Перевозчик')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('address', models.CharField(max_length=255, verbose_name='Объект')),
                ('responsible', models.CharField(max_length=255, verbose_name='Прораб')),
                ('closed', models.BooleanField(default=False, verbose_name='Исполнен')),
                ('notes', models.CharField(max_length=1000, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='OrderMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(blank=True, upload_to='order_media/%Y/%m/%d/', verbose_name='Файл к заявке')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordermedia', to='supply.orders', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Картинка к заявке',
                'verbose_name_plural': 'Картинки к заявке',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='N пп')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('unit', models.CharField(max_length=10, verbose_name='е.и.')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кол-во')),
                ('note', models.CharField(max_length=255, verbose_name='Примечание')),
                ('closed', models.BooleanField(default=False, verbose_name='Исполнен')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='supply.orders', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Строка заявки',
                'verbose_name_plural': 'Строки заявки',
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=100, verbose_name='Поставщик')),
                ('number', models.CharField(max_length=100, verbose_name='Номер')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='supply.orders', verbose_name='Счет')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='DeliverItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=500, verbose_name='Примечание')),
                ('deliver_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_item', to='supply.delivers', verbose_name='Доставка')),
                ('invoice', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='supply.invoices', verbose_name='Счет')),
            ],
            options={
                'verbose_name': 'Ходка',
                'verbose_name_plural': 'Ходки',
            },
        ),
    ]
